---
  - name: git completion
    copy: src=files/profile/git-completion.sh dest=/etc/profile.d/git-completion.sh mode=644

  - name: bash prompt
    copy: src=files/profile/prompt.sh dest=/etc/profile.d/prompt.sh mode=644 force=no

  - name: bash aliases
    copy: src=files/profile/aliases.sh dest=/etc/profile.d/aliases.sh mode=644 force=no

  - name: remove user profile
    file: path=.profile state=absent

  - name: remove user bashrc
    file: path=.bashrc state=absent

  - name: update apt-get
    apt: update-cache=yes
